{% set name = "nr.optional" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nr.optional-{{ version }}.tar.gz
  sha256: 1b801f73f50389625722647f6befe15d5b43e507f73ce35569a13efaa2df4c08

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - nr
    - nr.optional
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.niklasrosenstein.com/NiklasRosenstein/nr
  summary: Package description here.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - NiklasRosenstein
